import { readFileSync } from "node:fs";

const html = readFileSync(new URL("../index.html", import.meta.url), "utf8");

for (const required of [
  "3D Model Studio",
  "window.ModelerStudio",
  "METERS_PER_ROBLOX_STUD",
  "ROBLOX_STUDS_PER_METER",
  "preserveDrawingBuffer: true",
  "wedge: makeWedgeGeometry",
  "hollowBox: makeHollowBoxGeometry",
  "tube: () => makeRingLikeGeometry",
  "curvedPanel: makeCurvedPanelGeometry",
  "ring: () => makeRingLikeGeometry",
  "new THREE.ExtrudeGeometry(shape",
  "makeRingShape",
  "makeArcBandShape",
  "orientExtrudedGeometry",
  "arch: makeArchGeometry",
  "hemisphere: makeHemisphereGeometry",
  "dome: () => makeHemisphereGeometry",
  "capsule: () => new THREE.CapsuleGeometry",
  "pyramid: () => {",
  "prism: makePrismGeometry",
  "tetrahedron: () => new THREE.TetrahedronGeometry",
  "pyramidFrustum: () => {",
  "heart: makeHeartGeometry",
  "makeHemisphereGeometry",
  "makePrismGeometry",
  "makeHeartGeometry",
  "cutSpecFromObject",
  "applyGeometryCuts",
  "clipGeometrySide",
  "top-remove",
  "bottom-cut",
  "cutSideSelect",
  "cutAmountInput",
  "cutMeshBtn",
  "cutSelectedMesh",
  "Cut the selected part",
  "View Space",
  "Shot Zoom",
  "Show Grid",
  "Select Part Overlay",
  "Use Current Zoom In Shots",
  "Hide Grid In Shots",
  "previewFrontBtn",
  "previewBackBtn",
  "previewLeftBtn",
  "previewRightBtn",
  "previewTopBtn",
  "previewIsoBtn",
  "resetZoomBtn",
  "viewSpaceInput",
  "shotSpaceInput",
  "showGridInput",
  "showSelectionOverlayInput",
  "useCurrentZoomInShotsInput",
  "hideGridInShotsInput",
  "viewSpaceMultiplier",
  "shotSpaceMultiplier",
  "syncGridVisibility",
  "updateViewScale",
  "orbit.maxDistance",
  "stair: makeStairGeometry",
  "shapeAliases",
  "Hollow Box",
  "Curved Panel",
  "Half Sphere",
  "Dome",
  "Capsule",
  "Pyramid",
  "Prism",
  "Tetrahedron",
  "Pyramid Frustum",
  "Heart",
  "TransformControls",
  "Flip X",
  "Flip Y",
  "Flip Z",
  "data-flip-axis",
  "MTLLoader",
  "OBJExporter",
  "OrbitControls",
  "exportCollada",
  "exportColladaPackage",
  "Export Roblox Pack",
  "exportObjPartsBtn",
  "exportObjParts",
  "safeFileName",
  "Import every OBJ file as its own MeshPart in Roblox Studio.",
  "textureAssets",
  "Roblox Texture ID",
  "Mesh Details",
  "meshDetailsModal",
  "meshMaterialRuleSelect",
  "Open mesh details for",
  "materialRule",
  "Paper",
  "Upholstery",
  "selection highlight guides",
  "updateSelectionGuides",
  "Hide All",
  "Un Hide All",
  "textureRobloxAssetId",
  "reconcileTextureRobloxIds",
  "collectRobloxTextureCatalog",
  "downloadDataUrl",
  "captureViewsBtn",
  "Save Views",
  "captureView",
  "captureViews",
  "previewShotView",
  "screenshotViewDirections",
  "toDataURL(\"image/png\")",
  "reference screenshots for AI review",
  "Selection Tool",
  "Line Tool",
  "Marker Tool",
  "Tri Editor",
  "toolbarSelectionToolsGroup",
  "toolbarLineToolsGroup",
  "toolbarMarkerToolsGroup",
  "toolbarTriEditorGroup",
  "Face edit tools",
  "Select Tri",
  "Paint",
  "paintTriInput",
  "Area Select",
  "areaTriBtn",
  "areaTriInput",
  "selectionBox",
  "Clear Tri",
  "Delete Tri",
  "Extract Tri",
  "Fill Hole",
  "Remove Marks",
  "Copy Tri",
  "Paste Tri",
  "Extend",
  "Pull",
  "Push",
  "Drag/Push",
  "dragPushBtn",
  "dragPushAxisSelect",
  "dragPushStepInput",
  "Connect",
  "connectFaceInput",
  "rotationSnapSelect",
  "applyRotationSnap",
  "setRotationSnap",
  "markerBtn",
  "clearTriBtn",
  "areaTriBtn",
  "areaTriInput",
  "deleteTriBtn",
  "extractTriBtn",
  "fillHoleBtn",
  "removeMarksBtn",
  "copyTriBtn",
  "pasteTriBtn",
  "extendFaceBtn",
  "pullFaceBtn",
  "pushFaceBtn",
  "markerGroup",
  "markerHelpers",
  "selectedFaces",
  "selectedTriangles",
  "activeTransformMode",
  "setTransformMode",
  "updateTransformAttachment",
  "flipSelectedParts",
  "mirrorMeshGeometry",
  "Mirror selected part around its own",
  "triangleLocalPoints",
  "triangleLocalUvs",
  "worldTrianglePoints",
  "worldFaceNormal",
  "makeTriangleGeometry",
  "clearSelectedTriangles",
  "makeSelectionMarker",
  "makeSelectionMarkerBatch",
  "updateTriangleHelpers",
  "markerKey",
  "removeMarkerAt",
  "clearMarkers",
  "addMarkerFromSelectedTriangle",
  "removeMarkersForSelection",
  "clearTriangleSelection",
  "deleteSelectedTriangles",
  "extractSelectedTriangles",
  "deleteMarkersByTriangleSignatures",
  "triangleSignature",
  "vertexKey",
  "faceFromLocalTriangle",
  "meshTriangleFaces",
  "localUvs",
  "setTriangleSelection",
  "selectTrianglesInScreenRect",
  "connectedTriangleFaces",
  "selectConnectedTrianglesFromHit",
  "projectWorldPointToCanvas",
  "finishAreaSelection",
  "updateSelectionBox",
  "copySelectedTriangles",
  "pasteCopiedTriangles",
  "fillSelectedHole",
  "copiedTrianglePatch",
  "makeTrianglePatchSpec",
  "patchUvs",
  "textureUrl: firstMesh.userData.textureUrl",
  "textureFlipY: firstMesh.userData.textureFlipY",
  "paintTriangleFromPointer",
  "lastPaintLogAt",
  "performance.now",
  "finishTrianglePainting",
  "spaceCameraMode",
  "Hold Space to orbit camera",
  "Area mode: drag a rectangle",
  "dblclick",
  "Camera orbit override",
  "hitFromPointerEvent",
  "localTriangle",
  "redrawMarker",
  "extendSelectedFaces",
  "moveSelectedSideVertices",
  "connectedFaceDistance",
  "faceLengthResolver",
  "Extend selected triangle side",
  "mesh.userData.shape = \"custom\"",
  "mesh.userData.geometry = geometryToData(geometry)",
  "pullSelectedFaces",
  "pushSelectedFaces",
  "makePulledSelectionSpec",
  "addTriangleBothSides",
  "addQuadBothSides",
  "pulled triangle extrusion",
  "one editable extrusion",
  "transform.setSpace(activeTransformMode === \"rotate\" ? \"local\" : \"world\")",
  "pickFace(hit, { append: event.shiftKey })",
  "pickFace(hit, { append: true, toggleExisting: false, silent: true })",
  "Finished paint selection",
  "Hold Shift to add/remove more",
  "Click Marker again on the same triangle to remove it",
  "Triangle cursor: click a mesh triangle",
  "library_images",
  "TEXCOORD",
  "bind_vertex_input",
  "<diffuse><texture",
  "exportDaeBtn",
  "OBJLoader",
  "ColladaLoader",
  "importObjText",
  "importObjFiles",
  "importObjBtn",
  "importDaeText",
  "importDaeBtn",
  "importJsonData",
  "facePickBtn",
  "bevelFaceBtn",
  "bevelTypeSelect",
  "bevelSizeInput",
  "bevelDepthInput",
  "makeInsetBeveledPanelGeometry",
  "makeGeometryDataForShape",
  "textureInfoFromMaterial",
  "applyTextureToMesh",
  "textureUrl",
  "textureBtn",
  "rotateTextureBtn",
  "flipTextureBtn",
  "textureFile",
  "Add Texture",
  "Rotate Texture",
  "Flip Texture",
  "Clear Texture",
  "textureFlipY",
  "textureRotation",
  "transformTextureUv",
  "normalizeTextureRotation(-textureRotation)",
  "geometry.setAttribute(\"uv\"",
  "manager.setURLModifier",
  "pickFace",
  "bevelSelectedFace",
  "createBevelFacePatch",
  "coplanarConnectedFaces",
  "selected.material.transparent = false",
  "selected.material.opacity = 1",
  "selected.material.wireframe = false",
  "position.getX(i) * METERS_PER_ROBLOX_STUD",
  "unitScale: ROBLOX_STUDS_PER_METER",
  "preserveScale: true"
]) {
  if (!html.includes(required)) {
    throw new Error(`Missing expected editor feature: ${required}`);
  }
}

for (const removed of [
  "A" + "I Modeler Studio",
  "window.Modeler" + "A" + "I",
  "Ol" + "lama",
  "A" + "I Train" + "ing Hooks",
  "Reward " + "score",
  "Model " + "Prompt",
  "Fix " + "Feedback",
  "Ask Ol" + "lama",
  "Run " + "Batch",
  "batch" + "RunBtn",
  "prompt" + "Input",
  "feedback" + "Input",
  "edit" + "CommandInput",
  "draft" + "PlanFromPrompt",
  "askOl" + "lamaForPlan",
  "run" + "BatchAttempts",
  "export" + "BatchDataset",
  "fitSizeBtn",
  "fitSizeInput",
  "fitModelToSize",
  "Fit Size",
  "Target max model size",
  "addQuad(positions, of1, ob1, ib1, if1)",
  "addQuad(positions, ob0, of0, if0, ib0)",
  "aria-label=\"Primitive tools\"",
  "Pick Face",
  "new THREE.PlaneGeometry(Math.max(.05, width * .92)",
  "wireframe: true"
]) {
  if (html.includes(removed)) {
    throw new Error(`Removed feature still present: ${removed}`);
  }
}

for (const brokenText of ["Â", "â", "�"]) {
  if (html.includes(brokenText)) {
    throw new Error(`Corrupted text still present: ${brokenText}`);
  }
}

console.log("3D Model Studio smoke check passed.");
